### ISSUE TITLE
How to filter events for today or for this week?

### ISSUE THREAD

**Issue by svetlyak40wt** [davazp/cl-icalendar#3]
Hi @davazp!

David, is there a way to filter and get only events for today or for every day of the week?

I didn't find something like that in the sources.

**Comment by davazp** [comment]
Hi @svetlyak40wt,

As a disclaimer, I haven't used this library in a while so I don't remember 100% the details. But I hope I can help anyway.

The foundations to make that work should be there, but you'll have to put the pieces yourself a little bit, as a higher abstraction layer is unfortunately missing.

You want to filter `VEVENT` components of the calendar. To check if they are for today, for example, you can check a few properties like `DTSTART`, `DTEND`.  Think if you want to list them if they _start_ today or if they are just happening today. 

Do you also want to consider recurrent events? Then you'll want to use the functions exposed in `types-recur.lisp`. For example:

- `list-recur-instances` will give you occurrences of a recurrent event.
- `recur-instance-p` can be used to check for a specific date/time.

They value should be in the property `RRULE`. But there are other properties to exclude dates and so on. (https://tools.ietf.org/html/rfc5545#section-3.8.5.1).

So it is not difficult for easy cases, but if you want to have something 100% accurate, you'll have to go to the RFC document and read a bit how the VEVENT component works to interpret the properties.

**Comment by svetlyak40wt** [comment]
Well, I didn't find easy way :(

**Comment by davazp** [comment]
Sorry to hear that.  wish I had a bit more of time so I could have tried to help you.
