### ISSUE TITLE
Two tests fail on CCL 1.11.5

### ISSUE THREAD

**Issue by svetlyak40wt** [davazp/cl-icalendar#4]
```
 Did 93 checks.
    Pass: 91 (97%)
    Skip: 0 ( 0%)
    Fail: 2 ( 2%)

 Failure Details:
 --------------------------------
 RECUR-PARSER-COMPLEX-P-002 [Check parser for some complex syntax errors.]: 
      Unexpected Error: #<CCL::SIMPLE-PROGRAM-ERROR #x3020027DA63D>
:FORMAT-CONTROL is an invalid initarg to INITIALIZE-INSTANCE for #<STANDARD-CLASS CL-ICALENDAR::ICALENDAR-PARSE-ERROR>.
Valid initargs: (:STREAM :LINE :COLUMN)...
 --------------------------------
 --------------------------------
 FORMAT-UTC-OFFSET-001 []: 
      Failed to signal a ERROR.
 --------------------------------
```

**Comment by svetlyak40wt** [comment]
On SBCL 1.4.11 everything is fine:

```
 Did 93 checks.
    Pass: 93 (100%)
    Skip: 0 ( 0%)
    Fail: 0 ( 0%)
```

**Comment by svetlyak40wt** [comment]
Hyperspec says that:

Syntax:

error datum &rest arguments =>|

Arguments and Values:

datum, arguments---designators for a condition of default type simple-error.

But `icalendar-error` is inherited from the `error` class.

Don't know how does it work in SBCL, but seems that it just ignores tha fact that `'icalendar-parse-error` has no slot `format-control`, because this works in SBCL:

```
(make-condition 'icalendar-parse-error :format-control "test ~A ~A" :format-arguments (list :foo :bar))
```

But don't in CCL, and raises error:

```
:FORMAT-CONTROL is an invalid initarg to INITIALIZE-INSTANCE for #<STANDARD-CLASS ICALENDAR-PARSE-ERROR>.
Valid initargs: (:STREAM :LINE :COLUMN).
```

### Solution

To change definition of `calendar-error` to use `simple-error`, like this:

```
(define-condition icalendar-error (icalendar-condition simple-error)
  nil)
```

**Comment by svetlyak40wt** [comment]
@davazp will you accept the fix from "solution" section?

**Comment by davazp** [comment]
Hi @svetlyak40wt . Sorry I missed your original comment!  It makes sense. I applied the change. Thank you and sorry for the delay on this.

**Comment by svetlyak40wt** [comment]
Great, thank you!

**Comment by svetlyak40wt** [comment]
Actually, I'm testing a simple prototype of a tool, which helps to push pull requests and issues through a process of review. That is how I found this "lost" issue :)
